#!/usr/bin/env node
// npm run build — generate the shared references, then validate every skill.
//   (no args)         sync references, then validate
//   --sync-only       sync references only (what prepack runs)
//   --validate-only   validate only; assume the references are already synced
//
// bash is required for the sync and skills-ref is required for the validation,
// but they fail differently on purpose: a missing skills-ref is a skip, because
// validation is redundant on a release (the workflow already ran it) whereas a
// missing bash would publish a tarball with the generated references silently
// absent. So a missing bash is fatal, and a tool that runs and reports a
// problem is fatal either way.

import { spawnSync } from "node:child_process";
import { readdirSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const SKILLS_REF = join(ROOT, "node_modules", "skills-ref", "dist", "cli.js");

function run(label, file, args) {
  // Both streams to stderr: `npm pack --json` prints its own JSON on stdout, so
  // anything this script writes there corrupts that output.
  const r = spawnSync(file, args, { cwd: ROOT, stdio: ["ignore", 2, 2] });
  if (r.status !== 0) {
    console.error(`fail  ${label}: exit ${r.status ?? r.signal}`);
    process.exit(r.status ?? 1);
  }
  console.error(`ok    ${label}`);
}

console.error("building codebase-health\n");

const validateOnly = process.argv.includes("--validate-only");
const syncOnly = process.argv.includes("--sync-only");

if (!validateOnly) {
  // The generated references are gitignored build output, so a checkout that
  // skipped the sync publishes a tarball with three skills missing half their
  // references/. Never a skip: that failure is invisible until an installer
  // reports a dangling link.
  if (spawnSync("bash", ["--version"], { stdio: "ignore" }).error) {
    console.error(
      "fail  sync references: bash not on PATH.\n" +
        "      The per-skill references/ copies are generated by\n" +
        "      _shared/scripts/sync-references.sh, which needs bash. Install Git\n" +
        "      Bash, or run this from Git Bash / WSL / any POSIX shell.",
    );
    process.exit(1);
  }
  run("sync references", "bash", ["_shared/scripts/sync-references.sh"]);
}

if (syncOnly) {
  console.error("skip  validate skills: --sync-only");
} else if (!existsSync(SKILLS_REF)) {
  console.error("skip  validate skills: skills-ref not installed (npm i, then npm run validate)");
} else {
  // Expand the glob here: PowerShell does not glob native-command args, and
  // `skills-ref validate` accepts exactly one path.
  const skills = readdirSync(join(ROOT, "skills"), { withFileTypes: true })
    .filter((e) => e.isDirectory() && existsSync(join(ROOT, "skills", e.name, "SKILL.md")))
    .map((e) => `./skills/${e.name}`);
  for (const skill of skills) {
    run(`validate ${skill}`, process.execPath, [SKILLS_REF, "validate", skill]);
  }
}

console.error("\ndone");
